<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_produk_detail_model extends CI_Model
{

    public $table = 'm_produk_detail';
    public $id = 'id_produk_detail';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_produk_detail,nm_produk_detail,id_produk,id_produk_sub,harga,aktif');
        $this->datatables->from('m_produk_detail');
        //add this line for join
        //$this->datatables->join('table2', 'm_produk_detail.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('m_produk_detail/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed')) . "
            " . anchor(site_url('m_produk_detail/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed')) . "
                " . anchor(site_url('m_produk_detail/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_produk_detail');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_produk_detail', $q);
        $this->db->or_like('nm_produk_detail', $q);
        $this->db->or_like('id_produk', $q);
        $this->db->or_like('id_produk_sub', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('aktif', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_produk_detail', $q);
        $this->db->or_like('nm_produk_detail', $q);
        $this->db->or_like('id_produk', $q);
        $this->db->or_like('id_produk_sub', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('aktif', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function fetch_produk()
    {
        $this->db->where('aktif', 'Y');
        $this->db->order_by('nm_produk', 'ASC');
        $query = $this->db->get("m_produk");
        return $query->result();
    }
    function fetch_produk_sub($id_produk)
    {
        $this->db->where('id_produk', $id_produk);
        $this->db->where('aktif', 'Y');
        $this->db->group_by('id_produk_sub');
        $this->db->order_by('nm_produk_sub', 'ASC');
        $query = $this->db->get('m_produk_sub');
        $output = '<option value="">Select Sub produk</option>';
        foreach ($query->result() as $row) {
            $output .= '<option value="' . $row->id_produk_sub . '">' . $row->nm_produk_sub . '</option>';
        }
        return $output;
    }
}

/* End of file M_produk_detail_model.php */
/* Location: ./application/models/M_produk_detail_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-12-20 09:32:44 */
/* http://harviacode.com */