<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_produk_paket_model extends CI_Model
{

    public $table = 'm_produk_paket';
    public $id = 'id_paket';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('a.id_paket,a.id_kategori,b.kategori,a.nm_paket,a.deskripsi,FORMAT(a.harga,2) as harga,if(a.aktif="y","AKTIF","TIDAK AKTIF") as aktif,a.create_by,a.create_date');
        $this->datatables->from('m_produk_paket a');
        //add this line for join
        $this->datatables->join('m_produk_kategori b', 'a.id_kategori = b.id_kategori');
        $this->datatables->add_column('action', anchor(site_url('m_produk_paket/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed')) . "
            " . anchor(site_url('m_produk_paket/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed')) . "
                " . anchor(site_url('m_produk_paket/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_paket');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_paket', $q);
        $this->db->or_like('id_kategori', $q);
        $this->db->or_like('nm_paket', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('aktif', $q);
        $this->db->or_like('create_by', $q);
        $this->db->or_like('create_date', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_paket', $q);
        $this->db->or_like('id_kategori', $q);
        $this->db->or_like('nm_paket', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('aktif', $q);
        $this->db->or_like('create_by', $q);
        $this->db->or_like('create_date', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file M_produk_paket_model.php */
/* Location: ./application/models/M_produk_paket_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-30 08:02:56 */
/* http://harviacode.com */