<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_invoice_model extends CI_Model
{

    public $table = 't_invoice';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,
        no_invoice,
        tgl_invoice,
        users,
        create_date,
        status,
        id_pelanggan,
        nama,
        alamat,
        email,
        hp,nm_sales');
        $this->datatables->from('v_invoice');
        //add this line for join
        //$this->datatables->join('table2', 't_invoice.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t_invoice/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs waves-effect waves-themed')) . "
            " . anchor(site_url('t_invoice/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-xs waves-effect waves-themed')) . "
                " . anchor(site_url('t_invoice/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-xs waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('v_invoice')->row();
    }

    function get_pembayaran($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('v_invoice')->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('no_invoice', $q);
        $this->db->or_like('tgl_invoice', $q);
        $this->db->or_like('id_pelanggan', $q);
        $this->db->or_like('users', $q);
        $this->db->or_like('create_date', $q);
        $this->db->or_like('id_status', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('no_invoice', $q);
        $this->db->or_like('tgl_invoice', $q);
        $this->db->or_like('id_pelanggan', $q);
        $this->db->or_like('users', $q);
        $this->db->or_like('create_date', $q);
        $this->db->or_like('id_status', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file T_invoice_model.php */
/* Location: ./application/models/T_invoice_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-31 08:54:39 */
/* http://harviacode.com */