<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_keuangan_model extends CI_Model
{

    public $table = 't_keuangan';
    public $view = 'v_keuangan';
    public $id = 'id_buku';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function json()
    {
        $this->datatables->select('id_buku,note,created_date,created_by,debit,kredit');
        $this->datatables->from('v_keuangan');
        //add this line for join
        //$this->datatables->join('table2', 't_invoice.field = table2.field');
        $this->datatables->order_by('created_date', 'DESC');
        $this->datatables->add_column('action', anchor(site_url('t_keuangan/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs waves-effect waves-themed')) . "
            " . anchor(site_url('t_keuangan/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-xs waves-effect waves-themed')) . "
                " . anchor(site_url('t_keuangan/delete/$1'), '<i class="fal fa-trash" aria-hidden="true"></i>', 'class="btn btn-danger btn-xs waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('created_date', 'DESC');
        return $this->db->get('v_keuangan')->result();
    }

    function get_lapprojek()
    {
        $this->db->order_by('create_date', 'DESC');
        return $this->db->get('v_laporan_projek')->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_buku', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('note', $q);
        $this->db->or_like('debit', $q);
        $this->db->or_like('kredit', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('created_by', $q);
        $this->db->from($this->view);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by('created_date', 'DESC');
        $this->db->like('id_buku', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('note', $q);
        $this->db->or_like('debit', $q);
        $this->db->or_like('kredit', $q);
        $this->db->or_like('created_date', $q);
        $this->db->or_like('created_by', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->view)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file T_keuangan_model.php */
/* Location: ./application/models/T_keuangan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-01 13:41:36 */
/* http://harviacode.com */