<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_pesanan_model extends CI_Model
{

    public $table = 't_pesanan';
    public $id = 'id_pesanan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pesanan', $q);
	$this->db->or_like('no_pesanan', $q);
	$this->db->or_like('id_survei', $q);
	$this->db->or_like('id_tipe_pesanan', $q);
	$this->db->or_like('id_jenis_bahan', $q);
	$this->db->or_like('p', $q);
	$this->db->or_like('l', $q);
	$this->db->or_like('t', $q);
	$this->db->or_like('note', $q);
	$this->db->or_like('id_status', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('users', $q);
	$this->db->or_like('is_deleted', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pesanan', $q);
	$this->db->or_like('no_pesanan', $q);
	$this->db->or_like('id_survei', $q);
	$this->db->or_like('id_tipe_pesanan', $q);
	$this->db->or_like('id_jenis_bahan', $q);
	$this->db->or_like('p', $q);
	$this->db->or_like('l', $q);
	$this->db->or_like('t', $q);
	$this->db->or_like('note', $q);
	$this->db->or_like('id_status', $q);
	$this->db->or_like('created_date', $q);
	$this->db->or_like('users', $q);
	$this->db->or_like('is_deleted', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_pesanan_model.php */
/* Location: ./application/models/T_pesanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-12-08 06:31:26 */
/* http://harviacode.com */