<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_permintaan_model extends CI_Model
{

    public $table = 't_permintaan';
    public $id = 'id_permintaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_permintaan,jenis_permintaan,id_pelanggan,id_barang,qty,deskripsi,id_users,create_by,create_date');
        $this->datatables->from('t_permintaan');
        //add this line for join
        //$this->datatables->join('table2', 't_permintaan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t_permintaan/read/$1'),'<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed'))." 
            ".anchor(site_url('t_permintaan/update/$1'),'<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed'))." 
                ".anchor(site_url('t_permintaan/delete/$1'),'<i class="fal fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_permintaan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_permintaan', $q);
	$this->db->or_like('jenis_permintaan', $q);
	$this->db->or_like('id_pelanggan', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('create_by', $q);
	$this->db->or_like('create_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_permintaan', $q);
	$this->db->or_like('jenis_permintaan', $q);
	$this->db->or_like('id_pelanggan', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('create_by', $q);
	$this->db->or_like('create_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_permintaan_model.php */
/* Location: ./application/models/T_permintaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-13 05:39:17 */
/* http://harviacode.com */