<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Web_benefit_model extends CI_Model
{

    public $table = 'web_benefit';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,benefit_title,benefit_deskripsi,benefit_file,benefit_icon_1,benefit_title_1,benefit_desk_1,benefit_icon_2,benefit_title_2,benefit_desk_2,benefit_icon_3,benefit_title_3,benefit_desk_3');
        $this->datatables->from('web_benefit');
        $this->datatables->where('id', '1');
        //add this line for join
        //$this->datatables->join('table2', 'web_benefit.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('web_benefit/read/$1'), '<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed')) . " 
            " . anchor(site_url('web_benefit/update/$1'), '<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed')), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('benefit_title', $q);
        $this->db->or_like('benefit_deskripsi', $q);
        $this->db->or_like('benefit_file', $q);
        $this->db->or_like('benefit_icon_1', $q);
        $this->db->or_like('benefit_title_1', $q);
        $this->db->or_like('benefit_desk_1', $q);
        $this->db->or_like('benefit_icon_2', $q);
        $this->db->or_like('benefit_title_2', $q);
        $this->db->or_like('benefit_desk_2', $q);
        $this->db->or_like('benefit_icon_3', $q);
        $this->db->or_like('benefit_title_3', $q);
        $this->db->or_like('benefit_desk_3', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('benefit_title', $q);
        $this->db->or_like('benefit_deskripsi', $q);
        $this->db->or_like('benefit_file', $q);
        $this->db->or_like('benefit_icon_1', $q);
        $this->db->or_like('benefit_title_1', $q);
        $this->db->or_like('benefit_desk_1', $q);
        $this->db->or_like('benefit_icon_2', $q);
        $this->db->or_like('benefit_title_2', $q);
        $this->db->or_like('benefit_desk_2', $q);
        $this->db->or_like('benefit_icon_3', $q);
        $this->db->or_like('benefit_title_3', $q);
        $this->db->or_like('benefit_desk_3', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Web_benefit_model.php */
/* Location: ./application/models/Web_benefit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-28 08:35:30 */
/* http://harviacode.com */