<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Web_testimoni_model extends CI_Model
{

    public $table = 'web_testimoni';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,client_name,client_desk,client_testi,client_rate,aktif,client_foto');
        $this->datatables->from('web_testimoni');
        //add this line for join
        //$this->datatables->join('table2', 'web_testimoni.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('web_testimoni/read/$1'),'<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed'))." 
            ".anchor(site_url('web_testimoni/update/$1'),'<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed'))." 
                ".anchor(site_url('web_testimoni/delete/$1'),'<i class="fal fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('client_name', $q);
	$this->db->or_like('client_desk', $q);
	$this->db->or_like('client_testi', $q);
	$this->db->or_like('client_rate', $q);
	$this->db->or_like('aktif', $q);
	$this->db->or_like('client_foto', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('client_name', $q);
	$this->db->or_like('client_desk', $q);
	$this->db->or_like('client_testi', $q);
	$this->db->or_like('client_rate', $q);
	$this->db->or_like('aktif', $q);
	$this->db->or_like('client_foto', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Web_testimoni_model.php */
/* Location: ./application/models/Web_testimoni_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-28 08:48:27 */
/* http://harviacode.com */