<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Web_projek_model extends CI_Model
{

    public $table = 'web_projek';
    public $id = 'id_projek';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_projek,id_produk,projek_name,projek_lokasi,projek_start,projek_end,projek_desk,aktif');
        $this->datatables->from('web_projek');
        //add this line for join
        //$this->datatables->join('table2', 'web_projek.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('web_projek/read/$1'),'<i class="fal fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-sm waves-effect waves-themed'))." 
            ".anchor(site_url('web_projek/update/$1'),'<i class="fal fa-pencil" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm waves-effect waves-themed'))." 
                ".anchor(site_url('web_projek/delete/$1'),'<i class="fal fa-trash" aria-hidden="true"></i>','class="btn btn-danger btn-sm waves-effect waves-themed" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_projek');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_projek', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('projek_name', $q);
	$this->db->or_like('projek_lokasi', $q);
	$this->db->or_like('projek_start', $q);
	$this->db->or_like('projek_end', $q);
	$this->db->or_like('projek_desk', $q);
	$this->db->or_like('aktif', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_projek', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('projek_name', $q);
	$this->db->or_like('projek_lokasi', $q);
	$this->db->or_like('projek_start', $q);
	$this->db->or_like('projek_end', $q);
	$this->db->or_like('projek_desk', $q);
	$this->db->or_like('aktif', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Web_projek_model.php */
/* Location: ./application/models/Web_projek_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-28 08:42:57 */
/* http://harviacode.com */